delete from egswtax_billgeneration;

insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 1', 'Block1A', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B1A'));
insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 2', 'Block1B', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B1B'));
insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 3', 'Block2A', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B2A'));
insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 4', 'Block2B', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B2B'));
insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 5', 'Block3A', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B3A'));
insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 6', 'Block3B', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B3B'));
insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 7', 'Block4A', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B4A'));
insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 8', 'Block4B', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B4B'));
insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 9', 'Block5A', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B5A'));
insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 10', 'Block5B', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B5B'));
insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 11', 'Block6A', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B6A'));
insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 12', 'Block6B', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B6B'));
insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 13', 'Block7A', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B7A'));
insert into egswtax_billgeneration (batchname, boundarytype, boundary) values ('Batch 14', 'Block7B', (select id from eg_boundary where boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Block') and code='B7B'));



