update eg_boundary set parent=(select id from eg_boundary where code='B1'), name='SHAHPUR ROAD / LAMINI / KAJIPURA / TEACHER COLONY / GREEN FIELD COLONY / SINGPURA / GOPAL NAGAR / PATEL NAGAR',localname='SHAHPUR ROAD / LAMINI / KAJIPURA / TEACHER COLONY / GREEN FIELD COLONY / SINGPURA / GOPAL NAGAR / PATEL NAGAR' where code='PTK_1';
update eg_boundary set parent=(select id from eg_boundary where code='B2'), name='GOPAL NAGAR / SHAHPUR CHOWNK / MISSION ROAD / MAIN BAZAR / SHIMLA PAHARI / KABIR NAGAR / GARDEN COLONY / ISSA NAGAR',localname='GOPAL NAGAR / SHAHPUR CHOWNK / MISSION ROAD / MAIN BAZAR / SHIMLA PAHARI / KABIR NAGAR / GARDEN COLONY / ISSA NAGAR' where code='PTK_2';
update eg_boundary set parent=(select id from eg_boundary where code='B3'), name='MAIN BAZAR / MISSION ROAD / GARTHOLI MOHALLA',localname='MAIN BAZAR / MISSION ROAD / GARTHOLI MOHALLA' where code='PTK_3';
update eg_boundary set parent=(select id from eg_boundary where code='B4'), name='GARTHOLI MOHALLA / RAMLILA GROUND / MISSION ROAD',localname='GARTHOLI MOHALLA / RAMLILA GROUND / MISSION ROAD' where code='PTK_4';
update eg_boundary set parent=(select id from eg_boundary where code='B5'), name='MISSION ROAD / RAMLILA GROUND / NEHRU NAGAR / DALHOUSIE ROAD / SHARDA NAGAR / SDM COURT / GALI RAJ PAL SINGH / GARDEN COLONY / SHRI RAM MARKET DALHOUSIE ROAD',localname='MISSION ROAD / RAMLILA GROUND / NEHRU NAGAR / DALHOUSIE ROAD / SHARDA NAGAR / SDM COURT / GALI RAJ PAL SINGH / GARDEN COLONY / SHRI RAM MARKET DALHOUSIE ROAD' where code='PTK_5';
update eg_boundary set parent=(select id from eg_boundary where code='B6'), name='POST OFFICE / MAIN BAZAR / GANDHI CHOWK / GAHRI AHATA / MUNICIPAL BAZAR / DALHOUSIE ROAD / DHANGU CHOWK',localname='POST OFFICE / MAIN BAZAR / GANDHI CHOWK / GAHRI AHATA / MUNICIPAL BAZAR / DALHOUSIE ROAD / DHANGU CHOWK' where code='PTK_6';
update eg_boundary set parent=(select id from eg_boundary where code='B7'), name='GAHRI AHATA / GHARTHOLI MOHALLA',localname='GAHRI AHATA / GHARTHOLI MOHALLA' where code='PTK_7';
update eg_boundary set parent=(select id from eg_boundary where code='B8'), name='KALI MATA MANDIR ROAD / GAHRI AHATA CHOWK / DHANGU ROAD / GURJEET MARKET / PUSHAP PALACE / CAMBEL ROAD / MOHALLA KHADIAN / REKTA COMPLEX',localname='KALI MATA MANDIR ROAD / GAHRI AHATA CHOWK / DHANGU ROAD / GURJEET MARKET / PUSHAP PALACE / CAMBEL ROAD / MOHALLA KHADIAN / REKTA COMPLEX' where code='PTK_8';
update eg_boundary set parent=(select id from eg_boundary where code='B9'), name='RAMPURA / GURU NANAK NAGAR / RAMPURA DALHOUSIE ROAD / PREET NAGAR / SHASTRI NAGAR / BHADROYA ROAD / RAMPURA JHUGIAN',localname='RAMPURA / GURU NANAK NAGAR / RAMPURA DALHOUSIE ROAD / PREET NAGAR / SHASTRI NAGAR / BHADROYA ROAD / RAMPURA JHUGIAN' where code='PTK_9';
update eg_boundary set parent=(select id from eg_boundary where code='B10'), name='DALHOUSIE ROAD / BHADROYA ROAD / PROFESOR COLONY / KANSHI NAGAR / ISHAWAR NAGAR / TEACHER COLONY / KRISHNA NAGAR / AMBEDKAR NAGAR / SHASTRI NAGAR',localname='DALHOUSIE ROAD / BHADROYA ROAD / PROFESOR COLONY / KANSHI NAGAR / ISHAWAR NAGAR / TEACHER COLONY / KRISHNA NAGAR / AMBEDKAR NAGAR / SHASTRI NAGAR' where code='PTK_10';
update eg_boundary set parent=(select id from eg_boundary where code='B11'), name='DHANGU ROAD / JODHA MAL COLONY / SHANKAR COLONY / LIC LANE / PURANI SABZI MANDI / SHAVAJI NAGAR / SALARIA NAGAR / PATEL NAGAR / EKTA BIHAR / IMPORVEMENT TRUST / JAI RAM COLONY / GREEN AVENUE / ROSE AVENUE / DASHMESH NAGAR / SIALLI ROAD',localname='DHANGU ROAD / JODHA MAL COLONY / SHANKAR COLONY / LIC LANE / PURANI SABZI MANDI / SHAVAJI NAGAR / SALARIA NAGAR / PATEL NAGAR / EKTA BIHAR / IMPORVEMENT TRUST / JAI RAM COLONY / GREEN AVENUE / ROSE AVENUE / DASHMESH NAGAR / SIALLI ROAD' where code='PTK_11';
update eg_boundary set parent=(select id from eg_boundary where code='B12'), name='ONKAR NAGAR BHADROYA / AMBEDKAR NAGAR / PREET NAGAR / PLOT CHURH SINGH / FRIENDS COLONY / SIALLI ROAD / HARI GARDEN COLONY / BASANT COLONY / ADARSH COLONY / BEAUTY AVENUE',localname='ONKAR NAGAR BHADROYA / AMBEDKAR NAGAR / PREET NAGAR / PLOT CHURH SINGH / FRIENDS COLONY / SIALLI ROAD / HARI GARDEN COLONY / BASANT COLONY / ADARSH COLONY / BEAUTY AVENUE' where code='PTK_12';
update eg_boundary set parent=(select id from eg_boundary where code='B13'), name='GALI NO. 2 / SHIVAJI NAGAR / NATHU NAGAR',localname='GALI NO. 2 / SHIVAJI NAGAR / NATHU NAGAR' where code='PTK_13';
update eg_boundary set parent=(select id from eg_boundary where code='B14'), name='DHANGU PEER / SIALLI KULLIAN / SHIV SUNDER NAGAR / BANK COLONY / DHANGU ROAD / FRIENDS COLONY / SHIV NAAG MANDIR / GURU GOBIND SINGH NAGAR / SHAKTI NAGAR / ANGOORAN WALA BAAG',localname='DHANGU PEER / SIALLI KULLIAN / SHIV SUNDER NAGAR / BANK COLONY / DHANGU ROAD / FRIENDS COLONY / SHIV NAAG MANDIR / GURU GOBIND SINGH NAGAR / SHAKTI NAGAR / ANGOORAN WALA BAAG' where code='PTK_14';
update eg_boundary set parent=(select id from eg_boundary where code='B15'), name='SUNDER NAGAR / DHANGU ROAD',localname='SUNDER NAGAR / DHANGU ROAD' where code='PTK_15';
update eg_boundary set parent=(select id from eg_boundary where code='B16'), name='SUNDER NAGAR / DHANGU ROAD',localname='SUNDER NAGAR / DHANGU ROAD' where code='PTK_16';
update eg_boundary set parent=(select id from eg_boundary where code='B17'), name='CHMERA REST HOUSE / DHAKKI PIND / LAKSHMI GARDEN COLONY',localname='CHMERA REST HOUSE / DHAKKI PIND / LAKSHMI GARDEN COLONY' where code='PTK_17';
update eg_boundary set parent=(select id from eg_boundary where code='B18'), name='PURAN NAGAR / MUD HUT COLONY / DHANDU ROAD',localname='PURAN NAGAR / MUD HUT COLONY / DHANDU ROAD' where code='PTK_18';
update eg_boundary set parent=(select id from eg_boundary where code='B19'), name='MODEL TOWN',localname='MODEL TOWN' where code='PTK_19';
update eg_boundary set parent=(select id from eg_boundary where code='B20'), name='MODEL TOWN / MAHIR PUR COLONY',localname='MODEL TOWN / MAHIR PUR COLONY' where code='PTK_20';
update eg_boundary set parent=(select id from eg_boundary where code='B21'), name='MAHIR PUR COLONY / BHARAT NAGAR / CHAR MARLA RAM NAGAR',localname='MAHIR PUR COLONY / BHARAT NAGAR / CHAR MARLA RAM NAGAR' where code='PTK_21';
update eg_boundary set parent=(select id from eg_boundary where code='B22'), name='DHAKKI ROAD / NEHRU NAGAR / BHARAT NAGAR / PRATAP NAGAR / NROT COLONY / SABJI MANDI / NAVIABADI / BALA JI NAGAR / COLLEGE ROAD',localname='DHAKKI ROAD / NEHRU NAGAR / BHARAT NAGAR / PRATAP NAGAR / NROT COLONY / SABJI MANDI / NAVIABADI / BALA JI NAGAR / COLLEGE ROAD' where code='PTK_22';
update eg_boundary set parent=(select id from eg_boundary where code='B23'), name='SAINGAR / PREM NAGAR / MODELHIGH SCHOOL SAINGAR',localname='SAINGAR / PREM NAGAR / MODELHIGH SCHOOL SAINGAR' where code='PTK_23';
update eg_boundary set parent=(select id from eg_boundary where code='B24'), name='SAINGAR MAHAVIR SCHOOL / PREM NAGAR SAINGAR / DHANGU ROAD / KRISHNA NAGAR / CEPRI HOTEL / BAJRI COMPANY / JODHA MAL BAGH / PROFESOR COLONY / MAHAVIR PUBLIC SCHOOL',localname='SAINGAR MAHAVIR SCHOOL / PREM NAGAR SAINGAR / DHANGU ROAD / KRISHNA NAGAR / CEPRI HOTEL / BAJRI COMPANY / JODHA MAL BAGH / PROFESOR COLONY / MAHAVIR PUBLIC SCHOOL' where code='PTK_24';
update eg_boundary set parent=(select id from eg_boundary where code='B25'), name='4 MARLA RAM NAGAR / SHIV PURA / RAJINDER NAGAR',localname='4 MARLA RAM NAGAR / SHIV PURA / RAJINDER NAGAR' where code='PTK_25';
update eg_boundary set parent=(select id from eg_boundary where code='B26'), name='JODAMAL BAGH / BAJRI COMPANY / SHIV NAGAR',localname='JODAMAL BAGH / BAJRI COMPANY / SHIV NAGAR' where code='PTK_26';
update eg_boundary set parent=(select id from eg_boundary where code='B27'), name='PREM NAGAR DHAAKI ROAD / COLLEGE ROAD / MUNICIPAL COLONY / MOHALA TARA GURU / DOLATPUR / KATHALOR COLONY / ANMOL COLONY / DOLATPUR VADDA / RAVI DASS NAGAR / NEHRU CHOWNK / DHAKKI ROAD',localname='PREM NAGAR DHAAKI ROAD / COLLEGE ROAD / MUNICIPAL COLONY / MOHALA TARA GURU / DOLATPUR / KATHALOR COLONY / ANMOL COLONY / DOLATPUR VADDA / RAVI DASS NAGAR / NEHRU CHOWNK / DHAKKI ROAD' where code='PTK_27';
update eg_boundary set parent=(select id from eg_boundary where code='B28'), name='PICHE PETROL PUMP / DHAKKI ROAD / PREM NAGAR / RAVI DASS NAGAR / MOHALLA CHOTTA DOLATPUR / NEW ABADI',localname='PICHE PETROL PUMP / DHAKKI ROAD / PREM NAGAR / RAVI DASS NAGAR / MOHALLA CHOTTA DOLATPUR / NEW ABADI' where code='PTK_28';
update eg_boundary set parent=(select id from eg_boundary where code='B29'), name='MOHALLA COLLEGE ROAD / SAHMNE BAKSHI TIMBER / BERMA SALE ROAD / MOHALLA BAJRI COMPANY / GALA MANDI ROAD',localname='MOHALLA COLLEGE ROAD / SAHMNE BAKSHI TIMBER / BERMA SALE ROAD / MOHALLA BAJRI COMPANY / GALA MANDI ROAD' where code='PTK_29';
update eg_boundary set parent=(select id from eg_boundary where code='B30'), name='GURDASPUR ROAD / MOHALLA RAM GARIYA GURDASPUR ROAD / MOHALLA GANDHI NAGAR',localname='GURDASPUR ROAD / MOHALLA RAM GARIYA GURDASPUR ROAD / MOHALLA GANDHI NAGAR' where code='PTK_30';
update eg_boundary set parent=(select id from eg_boundary where code='B31'), name='DHANGU CHOWK / GANDHI CHOWK',localname='DHANGU CHOWK / GANDHI CHOWK' where code='PTK_31';
update eg_boundary set parent=(select id from eg_boundary where code='B32'), name='MOHALLA SUPER BAZZAR / SARAIN MOHALLA / MOHALLA INDIRA COLONY / RAILWAY ROAD',localname='MOHALLA SUPER BAZZAR / SARAIN MOHALLA / MOHALLA INDIRA COLONY / RAILWAY ROAD' where code='PTK_32';
update eg_boundary set parent=(select id from eg_boundary where code='B33'), name='MOHALLA ABROL NAGAR / BALWAN COLONY / ABROL NAGAR / MOHALLA ROJ BOOR AVENUE ABROL NAGAR / MOHALLA INDRA COLONY / NEW BANK COLONY / SHASTRI NAGAR / MOHALLA AMRUDA WALI CHUGIYAN / GURDASPUR ROAD / PATEL NAGAR / SHIV NAAG MANDIR / MOHALLA GURDASPUR ROAD',localname='MOHALLA ABROL NAGAR / BALWAN COLONY / ABROL NAGAR / MOHALLA ROJ BOOR AVENUE ABROL NAGAR / MOHALLA INDRA COLONY / NEW BANK COLONY / SHASTRI NAGAR / MOHALLA AMRUDA WALI CHUGIYAN / GURDASPUR ROAD / PATEL NAGAR / SHIV NAAG MANDIR / MOHALLA GURDASPUR ROAD' where code='PTK_33';
update eg_boundary set parent=(select id from eg_boundary where code='B34'), name='ANANDPUR / INDRA COLONY',localname='ANANDPUR / INDRA COLONY' where code='PTK_34';
update eg_boundary set parent=(select id from eg_boundary where code='B35'), name='MOHALLA SARAIN',localname='MOHALLA SARAIN' where code='PTK_35';
update eg_boundary set parent=(select id from eg_boundary where code='B36'), name='GOPIPURA / SANT NAGAR / ADRUN BAZAAR / MAIN BAZAAR',localname='GOPIPURA / SANT NAGAR / ADRUN BAZAAR / MAIN BAZAAR' where code='PTK_36';
update eg_boundary set parent=(select id from eg_boundary where code='B37'), name='SANT NAGAR / KAJIYA',localname='SANT NAGAR / KAJIYA' where code='PTK_37';
update eg_boundary set parent=(select id from eg_boundary where code='B38'), name='MOHALLA KAJIYA / MOHALLA RAJARHIYAN',localname='MOHALLA KAJIYA / MOHALLA RAJARHIYAN' where code='PTK_38';
update eg_boundary set parent=(select id from eg_boundary where code='B39'), name='MOHALLA JANDRIYAN / ARJUN NAGAR / ANANDPUR ROAD',localname='MOHALLA JANDRIYAN / ARJUN NAGAR / ANANDPUR ROAD' where code='PTK_39';
update eg_boundary set parent=(select id from eg_boundary where code='B40'), name='ANANDPUR / ANANDPUR KULLIYAN / ANANDPUR RARHA',localname='ANANDPUR / ANANDPUR KULLIYAN / ANANDPUR RARHA' where code='PTK_40';
update eg_boundary set parent=(select id from eg_boundary where code='B41'), name='NEW AWADI ANANDPUR / DHOBI GHAT / ARJUN NAGAR / ACHARJIYAN MOHALLA',localname='NEW AWADI ANANDPUR / DHOBI GHAT / ARJUN NAGAR / ACHARJIYAN MOHALLA' where code='PTK_41';
update eg_boundary set parent=(select id from eg_boundary where code='B42'), name='RAINA CHOWK / TILAK NAGAR / KARAM SINGH / MOH. JANDRIYAN / MOH. SAHIBJADIAN / AMRITSARIAN GALI',localname='RAINA CHOWK / TILAK NAGAR / KARAM SINGH / MOH. JANDRIYAN / MOH. SAHIBJADIAN / AMRITSARIAN GALI' where code='PTK_42';
update eg_boundary set parent=(select id from eg_boundary where code='B43'), name='ADROON BAZAR / MOH. KHARRA KHU / WADHERIAN MOHALLA / TILAK NAGAR',localname='ADROON BAZAR / MOH. KHARRA KHU / WADHERIAN MOHALLA / TILAK NAGAR' where code='PTK_43';
update eg_boundary set parent=(select id from eg_boundary where code='B44'), name='MOH. KASABA / MOH. ORRIAN / ADROON BAZAR',localname='MOH. KASABA / MOH. ORRIAN / ADROON BAZAR' where code='PTK_44';
update eg_boundary set parent=(select id from eg_boundary where code='B45'), name='ACHARJIYAN MOHALLA / SAHIB ZADIAN / SHAHPUR ROAD / NEW SHRI RAM COLONY / CIVIL HOSPITAL / KARAM SINGH NAGAR',localname='ACHARJIYAN MOHALLA / SAHIB ZADIAN / SHAHPUR ROAD / NEW SHRI RAM COLONY / CIVIL HOSPITAL / KARAM SINGH NAGAR' where code='PTK_45';
update eg_boundary set parent=(select id from eg_boundary where code='B46'), name='VISHKRMA NAGAR LAMINI / GOVT. SCHOOL LAMINI / SAHMANE TARSEM ATA CHAKKI / DEVA MANDIR / GALI LAJPAT RAI / RADHA SWAMI CHOWK / ARYA VEDIC DEV NAGARI / SWIMMING POOL / SAHIL GREEN PARK / GALI DR. KEWAL KRISHAN NAZDEEK M.C. TOWN',localname='VISHKRMA NAGAR LAMINI / GOVT. SCHOOL LAMINI / SAHMANE TARSEM ATA CHAKKI / DEVA MANDIR / GALI LAJPAT RAI / RADHA SWAMI CHOWK / ARYA VEDIC DEV NAGARI / SWIMMING POOL / SAHIL GREEN PARK / GALI DR. KEWAL KRISHAN NAZDEEK M.C. TOWN' where code='PTK_46';
update eg_boundary set parent=(select id from eg_boundary where code='B47'), name='CIVIL CHOWK / RAILWAY CROSSING / KHUSHI NAGAR / JAGAT NAGAR / RAM SHARNAM COLONY / RAM NAGAR / ROYAL AVENUE / SHANKAR NAGAR / BHADROYA / PIPLAN MOHALLA',localname='CIVIL CHOWK / RAILWAY CROSSING / KHUSHI NAGAR / JAGAT NAGAR / RAM SHARNAM COLONY / RAM NAGAR / ROYAL AVENUE / SHANKAR NAGAR / BHADROYA / PIPLAN MOHALLA' where code='PTK_47';


update egwtr_connection set locality=(select id from eg_boundary where code='PTK_47') where locality in (select id from eg_boundary where code not in ('PTK_1','PTK_2','PTK_3','PTK_4','PTK_5','PTK_6','PTK_7','PTK_8','PTK_9','PTK_10','PTK_11','PTK_12','PTK_13','PTK_14','PTK_15','PTK_16',
'PTK_17','PTK_18','PTK_19','PTK_20','PTK_21','PTK_22','PTK_23','PTK_24','PTK_25','PTK_26','PTK_27','PTK_28','PTK_29','PTK_30','PTK_31','PTK_32',
'PTK_33','PTK_34','PTK_35','PTK_36','PTK_37','PTK_38','PTK_39','PTK_40','PTK_41','PTK_42','PTK_43','PTK_44','PTK_45','PTK_46','PTK_47'));

update egwtr_connection set block =(select parent from eg_boundary where code='PTK_47') where block  in (select parent from eg_boundary where code not in ('PTK_1','PTK_2','PTK_3','PTK_4','PTK_5','PTK_6','PTK_7','PTK_8','PTK_9','PTK_10','PTK_11','PTK_12','PTK_13','PTK_14','PTK_15','PTK_16',
'PTK_17','PTK_18','PTK_19','PTK_20','PTK_21','PTK_22','PTK_23','PTK_24','PTK_25','PTK_26','PTK_27','PTK_28','PTK_29','PTK_30','PTK_31','PTK_32',
'PTK_33','PTK_34','PTK_35','PTK_36','PTK_37','PTK_38','PTK_39','PTK_40','PTK_41','PTK_42','PTK_43','PTK_44','PTK_45','PTK_46','PTK_47'));

update egswtax_connection set locality=(select id from eg_boundary where code='PTK_47') where locality in (select id from eg_boundary where code not in ('PTK_1','PTK_2','PTK_3','PTK_4','PTK_5','PTK_6','PTK_7','PTK_8','PTK_9','PTK_10','PTK_11','PTK_12','PTK_13','PTK_14','PTK_15','PTK_16',
'PTK_17','PTK_18','PTK_19','PTK_20','PTK_21','PTK_22','PTK_23','PTK_24','PTK_25','PTK_26','PTK_27','PTK_28','PTK_29','PTK_30','PTK_31','PTK_32',
'PTK_33','PTK_34','PTK_35','PTK_36','PTK_37','PTK_38','PTK_39','PTK_40','PTK_41','PTK_42','PTK_43','PTK_44','PTK_45','PTK_46','PTK_47'));
update egswtax_connection set block =(select parent from eg_boundary where code='PTK_47') where block  in (select parent from eg_boundary where code not in ('PTK_1','PTK_2','PTK_3','PTK_4','PTK_5','PTK_6','PTK_7','PTK_8','PTK_9','PTK_10','PTK_11','PTK_12','PTK_13','PTK_14','PTK_15','PTK_16',
'PTK_17','PTK_18','PTK_19','PTK_20','PTK_21','PTK_22','PTK_23','PTK_24','PTK_25','PTK_26','PTK_27','PTK_28','PTK_29','PTK_30','PTK_31','PTK_32',
'PTK_33','PTK_34','PTK_35','PTK_36','PTK_37','PTK_38','PTK_39','PTK_40','PTK_41','PTK_42','PTK_43','PTK_44','PTK_45','PTK_46','PTK_47'));

 delete from eg_boundary where code not in ('PTK_1','PTK_2','PTK_3','PTK_4','PTK_5','PTK_6','PTK_7','PTK_8','PTK_9','PTK_10','PTK_11','PTK_12','PTK_13','PTK_14','PTK_15','PTK_16',
'PTK_17','PTK_18','PTK_19','PTK_20','PTK_21','PTK_22','PTK_23','PTK_24','PTK_25','PTK_26','PTK_27','PTK_28','PTK_29','PTK_30','PTK_31','PTK_32',
'PTK_33','PTK_34','PTK_35','PTK_36','PTK_37','PTK_38','PTK_39','PTK_40','PTK_41','PTK_42','PTK_43','PTK_44','PTK_45','PTK_46','PTK_47') and boundarytype=(select id from eg_boundary_type where hierarchytype = (select id from eg_hierarchy_type where name = 'REVENUE') and name='Locality') ;
