 ------------------START------------------
insert into eg_demand_reason_master(id, reasonmaster, category, isdebit, module,code,"order", create_date, modified_date,isdemand) values(nextval('seq_eg_demand_reason_master'),'Door to Door Collection Charges',2,'N',(select id from eg_module where name='Sewerage Tax Management'),'DOORTODOORCOLLECTIONCHARGES',0,now(),now(),true);

insert into eg_demand_reason (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select nextval('seq_eg_demand_reason'),(select id from eg_demand_reason_master where code='DOORTODOORCOLLECTIONCHARGES' and module=(select id from eg_module where name='Sewerage Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404017') from eg_installment_master inst where inst.id_module=(select id from eg_module where name='Sewerage Tax Management') and start_date in (select start_date from eg_installment_master where id_module=(select id from eg_module where name='Sewerage Tax Management') and inst.installment_type='Quarterly');


insert into eg_demand_reason_master(id, reasonmaster, category, isdebit, module,code,"order", create_date, modified_date,isdemand) values(nextval('seq_eg_demand_reason_master'),'Door to Door Collection Charges',2,'N',(select id from eg_module where name='Water Tax Management'),'DOORTODOORCOLLECTIONCHARGES',0,now(),now(),true);

insert into eg_demand_reason (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select nextval('seq_eg_demand_reason'),(select id from eg_demand_reason_master where code='DOORTODOORCOLLECTIONCHARGES' and module=(select id from eg_module where name='Water Tax Management')),inst.id, null, null, current_timestamp, current_timestamp, (select id from chartofaccounts where glcode='1404017') from eg_installment_master inst where inst.id_module=(select id from eg_module where name='Water Tax Management') and start_date in (select start_date from eg_installment_master where id_module=(select id from eg_module where name='Water Tax Management') and inst.installment_type='Quarterly');
-------------------END-------------------