--Installment 2017-18
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type, financial_year) VALUES (nextval('seq_eg_installment_master'), 12017, '2017-04-01 00:00:00', '2017-04-01 00:00:00', '2017-06-30 23:59:59', (select id from eg_module where name='Water Tax Management'), now(), '2017-2018-1', 'Quarterly', '2017-18');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type, financial_year) VALUES (nextval('seq_eg_installment_master'), 22017, '2017-04-01 00:00:00', '2017-07-01 00:00:00', '2017-09-30 23:59:59', (select id from eg_module where name='Water Tax Management'), now(), '2017-2018-2', 'Quarterly', '2017-18');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type, financial_year) VALUES (nextval('seq_eg_installment_master'), 32017, '2017-04-01 00:00:00', '2017-10-01 00:00:00', '2017-12-31 23:59:59', (select id from eg_module where name='Water Tax Management'), now(), '2017-2018-3', 'Quarterly', '2017-18');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type, financial_year) VALUES (nextval('seq_eg_installment_master'), 42017, '2017-04-01 00:00:00', '2018-01-01 00:00:00', '2018-03-31 23:59:59', (select id from eg_module where name='Water Tax Management'), now(), '2017-2018-4', 'Quarterly', '2017-18');

--Installment 2018-19
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type, financial_year) VALUES (nextval('seq_eg_installment_master'), 12018, '2018-04-01 00:00:00', '2018-04-01 00:00:00', '2018-06-30 23:59:59', (select id from eg_module where name='Water Tax Management'), now(), '2018-2019-1', 'Quarterly', '2018-19');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type, financial_year) VALUES (nextval('seq_eg_installment_master'), 22018, '2018-04-01 00:00:00', '2018-07-01 00:00:00', '2018-09-30 23:59:59', (select id from eg_module where name='Water Tax Management'), now(), '2018-2019-2', 'Quarterly', '2018-19');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type, financial_year) VALUES (nextval('seq_eg_installment_master'), 32018, '2018-04-01 00:00:00', '2018-10-01 00:00:00', '2018-12-31 23:59:59', (select id from eg_module where name='Water Tax Management'), now(), '2018-2019-3', 'Quarterly', '2018-19');
INSERT INTO eg_installment_master (id, installment_num, installment_year, start_date, end_date, id_module, lastupdatedtimestamp, description, installment_type, financial_year) VALUES (nextval('seq_eg_installment_master'), 42018, '2018-04-01 00:00:00', '2019-01-01 00:00:00', '2019-03-31 23:59:59', (select id from eg_module where name='Water Tax Management'), now(), '2018-2019-4', 'Quarterly', '2018-19');

--demand reason masters

INSERT INTO eg_demand_reason_master(id, reasonmaster, category, isdebit, module,code,"order", create_date, modified_date,isdemand) VALUES (nextval('seq_eg_demand_reason_master'), 'Water Charges', (select id from eg_reason_category where code='TAX'),'N',(select id from eg_module where name = 'Water Tax Management'),'WTAXCHARGES', 1, now(), now(),true);
INSERT INTO eg_demand_reason_master(id, reasonmaster, category, isdebit, module,code,"order", create_date, modified_date,isdemand) VALUES (nextval('seq_eg_demand_reason_master'), 'Penalty', (select id from eg_reason_category where code='PENALTY'),'N',(select id from eg_module where name = 'Water Tax Management'),'PENALTY', 1, now(), now(),true);
INSERT INTO eg_demand_reason_master(id, reasonmaster, category, isdebit, module,code,"order", create_date, modified_date,isdemand) VALUES (nextval('seq_eg_demand_reason_master'), 'Interest', (select id from eg_reason_category where code='FINES'),'N',(select id from eg_module where name = 'Water Tax Management'),'INTEREST', 1, now(), now(),true);

--demand reasons

Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Water Charges' and module=(select id from eg_module where name='Water Tax Management')), inst.id, null, null, current_timestamp, current_timestamp, null from eg_installment_master inst where inst.id_module=(select id from eg_module where name='Water Tax Management') and start_date in (select start_date from eg_installment_master where id_module=(select id from eg_module where name='Water Tax Management') and inst.installment_type='Quarterly');

Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Penalty' and module=(select id from eg_module where name='Water Tax Management')), inst.id, null, null, current_timestamp, current_timestamp, null from eg_installment_master inst where inst.id_module=(select id from eg_module where name='Water Tax Management') and start_date in (select start_date from eg_installment_master where id_module=(select id from eg_module where name='Water Tax Management') and inst.installment_type='Quarterly');

Insert into EG_DEMAND_REASON (ID,ID_DEMAND_REASON_MASTER,ID_INSTALLMENT,PERCENTAGE_BASIS,ID_BASE_REASON,create_date,modified_date,GLCODEID) select nextval('seq_eg_demand_reason'), (select id from eg_demand_reason_master where reasonmaster='Interest' and module=(select id from eg_module where name='Water Tax Management')), inst.id, null, null, current_timestamp, current_timestamp, null from eg_installment_master inst where inst.id_module=(select id from eg_module where name='Water Tax Management') and start_date in (select start_date from eg_installment_master where id_module=(select id from eg_module where name='Water Tax Management') and inst.installment_type='Quarterly');

