INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Apartment'), 0, 125, null, null,'2018-04-01', '2020-03-31', null, 100,'PLOT_BASED', now(), now(), 1,1,1);

INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Apartment'), 126, 250, null, null,'2018-04-01', '2020-03-31', null, 200,'PLOT_BASED', now(), now(), 1,1,1);

INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Apartment'), 250, null, null, null,'2018-04-01', '2020-03-31', null, 300,'PLOT_BASED', now(), now(), 1,1,1);

INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Residential'), 0, 125, null, null,'2018-04-01', '2020-03-31', null, 200,'PLOT_BASED', now(), now(), 1, 1,1);

INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Residential'), 126, 250, null, null,'2018-04-01', '2020-03-31', null, 300,'PLOT_BASED', now(), now(), 1, 1,1);

INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Residential'), 250, null, null, null,'2018-04-01', '2020-03-31', null, 400,'PLOT_BASED', now(), now(), 1, 1,1);


INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Apartment'), null, null, 1, 1,'2018-04-01', '2020-03-31', null, 10,'TAP_BASED', now(), now(), 1, 1,1);

INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Apartment'), null, null, 2, 2,'2018-04-01', '2020-03-31', null, 20,'TAP_BASED', now(), now(), 1, 1,1);

INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Apartment'), null, null, 3, null,'2018-04-01', '2020-03-31', null, 30,'TAP_BASED', now(), now(), 1, 1,1);

INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Residential'), null, null, 1, 1,'2018-04-01', '2020-03-31', null, 20,'TAP_BASED', now(), now(), 1, 1,1);

INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Residential'), null, null, 2, 2,'2018-04-01', '2020-03-31', null, 30,'TAP_BASED', now(), now(), 1, 1,1);

INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Residential'), null, null, 3, null,'2018-04-01', '2020-03-31', null, 40,'TAP_BASED', now(), now(), 1, 1,1);


INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Apartment'), null, null, null, null,'2018-04-01', '2020-03-31', 100, null,'FIXED', now(), now(), 1, 1,1);

INSERT INTO egwtr_watercharge_rates(id, usagetype, fromplotarea, toplotarea, fromnooftaps, tonooftaps,effectivefromdate, effectivetodate, fixedcharges, rateamount,ratetype, createddate, lastmodifieddate, createdby, lastmodifiedby,version)  VALUES (nextval('seq_egwtr_watercharge_rates'), (select id from egwtr_usage_type where name ='Residential'), null, null, null, null,'2018-04-01', '2020-03-31', 200, null,'FIXED', now(), now(), 1, 1,1);

